packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@medusajs/telemetry': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
